# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title
plugins: [jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :compressed

title: "BitDevs Toronto"
description: "BitDevs is a community for those interested in discussing and participating in the research and development of Bitcoin and related protocols."
url: "https://bitdevs.to"
timezone: America/Toronto
author: "BitDevs Toronto"

# Leave out some files
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.sass-cache']

future: true
